// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: aggregate.proto

package protomodels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Aggregate int32

const (
	Aggregate_Minimum Aggregate = 0
	Aggregate_Maximum Aggregate = 1
	Aggregate_Average Aggregate = 2
	Aggregate_Median  Aggregate = 3
	Aggregate_Sum     Aggregate = 4
	Aggregate_Count   Aggregate = 5
	Aggregate_Unknown Aggregate = 6
)

// Enum value maps for Aggregate.
var (
	Aggregate_name = map[int32]string{
		0: "Minimum",
		1: "Maximum",
		2: "Average",
		3: "Median",
		4: "Sum",
		5: "Count",
		6: "Unknown",
	}
	Aggregate_value = map[string]int32{
		"Minimum": 0,
		"Maximum": 1,
		"Average": 2,
		"Median":  3,
		"Sum":     4,
		"Count":   5,
		"Unknown": 6,
	}
)

func (x Aggregate) Enum() *Aggregate {
	p := new(Aggregate)
	*p = x
	return p
}

func (x Aggregate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aggregate) Descriptor() protoreflect.EnumDescriptor {
	return file_aggregate_proto_enumTypes[0].Descriptor()
}

func (Aggregate) Type() protoreflect.EnumType {
	return &file_aggregate_proto_enumTypes[0]
}

func (x Aggregate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aggregate.Descriptor instead.
func (Aggregate) EnumDescriptor() ([]byte, []int) {
	return file_aggregate_proto_rawDescGZIP(), []int{0}
}

var File_aggregate_proto protoreflect.FileDescriptor

var file_aggregate_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2a, 0x5f, 0x0a, 0x09, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d,
	0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x10,
	0x03, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x06, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aggregate_proto_rawDescOnce sync.Once
	file_aggregate_proto_rawDescData = file_aggregate_proto_rawDesc
)

func file_aggregate_proto_rawDescGZIP() []byte {
	file_aggregate_proto_rawDescOnce.Do(func() {
		file_aggregate_proto_rawDescData = protoimpl.X.CompressGZIP(file_aggregate_proto_rawDescData)
	})
	return file_aggregate_proto_rawDescData
}

var file_aggregate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aggregate_proto_goTypes = []any{
	(Aggregate)(0), // 0: Aggregate
}
var file_aggregate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aggregate_proto_init() }
func file_aggregate_proto_init() {
	if File_aggregate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aggregate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aggregate_proto_goTypes,
		DependencyIndexes: file_aggregate_proto_depIdxs,
		EnumInfos:         file_aggregate_proto_enumTypes,
	}.Build()
	File_aggregate_proto = out.File
	file_aggregate_proto_rawDesc = nil
	file_aggregate_proto_goTypes = nil
	file_aggregate_proto_depIdxs = nil
}
