// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/query": {
            "post": {
                "description": "Queries data with specified grouping and selection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Query data from a table",
                "parameters": [
                    {
                        "description": "Query Request",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.HttpQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query has been processed",
                        "schema": {
                            "$ref": "#/definitions/main.HttpResult"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Checks controller status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health check"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Health check passed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.HttpAggregateFunction": {
            "type": "string",
            "enum": [
                "Minimum",
                "Maximum",
                "Average"
            ],
            "x-enum-varnames": [
                "Minimum",
                "Maximum",
                "Average"
            ]
        },
        "main.HttpError": {
            "type": "object",
            "properties": {
                "inner_message": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "main.HttpPartialResult": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "is_null": {
                    "type": "boolean"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "main.HttpQueryRequest": {
            "type": "object",
            "properties": {
                "group_columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "select": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.HttpSelect"
                    }
                },
                "table_name": {
                    "type": "string"
                }
            }
        },
        "main.HttpQueryResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/main.HttpError"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.HttpValue"
                    }
                }
            }
        },
        "main.HttpResult": {
            "type": "object",
            "properties": {
                "processing_time": {
                    "type": "integer"
                },
                "result": {
                    "$ref": "#/definitions/main.HttpQueryResponse"
                }
            }
        },
        "main.HttpSelect": {
            "type": "object",
            "properties": {
                "column": {
                    "type": "string"
                },
                "function": {
                    "$ref": "#/definitions/main.HttpAggregateFunction"
                }
            }
        },
        "main.HttpValue": {
            "type": "object",
            "properties": {
                "grouping_value": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.HttpPartialResult"
                    }
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Distributed data aggregation system API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
