basePath: /api/v1
definitions:
  main.HttpAggregateFunction:
    enum:
    - Minimum
    - Maximum
    - Average
    type: string
    x-enum-varnames:
    - Minimum
    - Maximum
    - Average
  main.HttpError:
    properties:
      inner_message:
        type: string
      message:
        type: string
    type: object
  main.HttpPartialResult:
    properties:
      count:
        type: integer
      value:
        type: integer
    type: object
  main.HttpQueryRequest:
    properties:
      group_columns:
        items:
          type: string
        type: array
      select:
        items:
          $ref: '#/definitions/main.HttpSelect'
        type: array
      table_name:
        type: string
    type: object
  main.HttpQueryResponse:
    properties:
      error:
        $ref: '#/definitions/main.HttpError'
      values:
        items:
          $ref: '#/definitions/main.HttpValue'
        type: array
    type: object
  main.HttpResult:
    properties:
      processing_time:
        type: integer
      result:
        $ref: '#/definitions/main.HttpQueryResponse'
    type: object
  main.HttpSelect:
    properties:
      column:
        type: string
      function:
        $ref: '#/definitions/main.HttpAggregateFunction'
    type: object
  main.HttpValue:
    properties:
      grouping_value:
        type: string
      results:
        items:
          $ref: '#/definitions/main.HttpPartialResult'
        type: array
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact: {}
  title: Swagger Distributed data aggregation system API
  version: "1.0"
paths:
  /query:
    post:
      consumes:
      - application/json
      description: Queries data with specified grouping and selection
      parameters:
      - description: Query Request
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/main.HttpQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Query has been processed
          schema:
            $ref: '#/definitions/main.HttpResult'
        "400":
          description: Invalid request payload
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Query data from a table
      tags:
      - query
swagger: "2.0"
